service: feel-know-how-server
frameworkVersion: "2"
provider:
    name: aws
    runtime: nodejs12.x
    stage: prod
    region: ap-northeast-2
plugins:
    - serverless-webpack
    # - serverless-offline

custom:
    webpack:
        webpackConfig: "webpack.config.js"
        includeModules: true
        packager: "yarn"

functions:
    app:
        handler: src/app.handler
        events:
            - http:
                path: /
                method: ANY
                cors: true
            - http:
                path: "{proxy+}"
                method: ANY
                cors: true
            
package:
    individually: true
    include:
        - node_modules/**
