service: feel-know-how-server
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2


functions:
  app:
    handler: src/server.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
